- name: install maven
  ansible.builtin.dnf:
   name: " {{ item }} "
   state: present
  loop:
  - maven
  - mysql

- name: install PyMySQL and cryptography
  ansible.builtin.pip:
   name: " {{ item }} "
   executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: install maven dependencies
  ansible.builtin.command: mvn clean package 
  args: 
    chdir: /app   

- name: rename the shipping component
  ansible.builtin.command:  mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app
